Fixed the include name of the jsoncpp library

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -13,6 +13,7 @@ jobs:
       - name: Install dependencies and setup the environment
         run: |
           sudo apt install make cmake build-essential libboost-dev libbz2-dev libssl-dev libjsoncpp-dev libprotozero-dev -y
+          sudo ln -s /usr/include/jsoncpp/json /usr/include/json || echo "Failed to create symlink"
       - name: Checkout submodules
         run: |
           git submodule init
